### ISSUE TITLE
Does the .NET 7 API changed?

### ISSUE THREAD

**Issue by GF-Huang** [noelex/Quic.NET#1]
> `System.Net.Quic is` currently internal and scheduled to be delivered in .NET 7, which means the APIs are subject to change.

**Comment by noelex** [comment]
Yes. There're some minor breaking changes. Please review the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.net.quic?view=net-7.0) for details.

**Comment by GF-Huang** [comment]
Do you have any plans to update? For .NET 6.

**Comment by noelex** [comment]
I'm afraid no.

Since .NET 7 now officially supports QUIC, I don't see the benefit to update `Quic.NET` to match .NET's QUIC API.

You can either upgrade your project to .NET 7 to get official support, or  continue using `Quic.NET` if you'd like to stick with .NET 6, just remember that it won't be receiving any security update.

**Comment by GF-Huang** [comment]
Thanks your reply.
